### ISSUE TITLE
Does not load on Safari

### ISSUE THREAD

**Issue by h4llow3En** [newsic/newsic#1] opened 2016-04-18 19:59 UTC

**Comment by Feliix42** [comment] 2016-04-18 21:04
The problem is caused by a combination of my **uBlock** config and the missing support of Safari for default values in JS functions.

**Comment by h4llow3En** [comment] 2016-04-18 21:06
I deactivated ublock, didn't worked too

**Comment by Feliix42** [comment] 2016-04-18 21:06
And Ghostery :D

**Comment by Feliix42** [comment] 2016-04-18 21:07
![on it](http://i.giphy.com/RTGptCQyfIbqU.gif)

**Comment by tocsinDE** [comment] 2016-04-18 21:09
Missing ES6 specifications in Safari are fixed in the demo version since.. now. Seems like Safari + [blocker of your choice) has a problem with fetching the "https://geoip.nekudo.com/api" script.

**Comment by tocsinDE** [comment] 2017-02-14 16:53
Is this issue still relevant, @h4llow3En?

**Comment by h4llow3En** [comment] 2017-02-14 17:52
No, this was fixed

**Closed** 2017-02-14 18:08 UTC
Labels: JavaScript
